# Generated by Django 3.0.5 on 2020-05-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20200502_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='added_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
